
cache:
  directories:
    - ~/.npm

install:
  - npm install -g vsce
  - npm install -g typescript
  - npm install

script:
  - npm run lint
  - npm run test

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

jobs:
  include:
    - stage: release
      language: node_js
      node_js: '8'
      script: npm run semantic-release